# Generated by Django 5.2.9 on 2025-12-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmreport',
            name='total_production',
        ),
    ]
